### ISSUE TITLE
Indexing improvements

### ISSUE THREAD

**Issue by rcmolina** [DnCraptor/pico-spec#1]
Please,  look at 1.3 for sd files indexing algorithm. Much more usable version.

https://github.com/EremusOne/ESPectrum/commit/501e74a3ffe1b36abc3fc79e6960897ad502e206

Open this issue just to no not forget in your priority stack, not a bug.

**Comment by DnCraptor** [comment]
FYI: current port version (since v.0.3.1) contains fixed algo, not original, but quite fast. I'm not planning to port algo from 1.3 in nearest time.
Not sure, I will port 1.3 also.

**Comment by rcmolina** [comment]
Many thanks
