### ISSUE TITLE
Green pico uf2 flashing file size

### ISSUE THREAD

**Issue by rcmolina** [DnCraptor/pico-spec#2]
@DnCraptor, Flash memory for green pico is 2048 MB, but .uf2 file size released for versions>=0.3.0 is bigger. For me, not possible flashing these files from pico boot, stopped on 0.2.9 :( , can't test new features.

Any advice? Thanks for yor grate work.

Rafael

**Comment by DnCraptor** [comment]
There are prepared builds for 2MB - https://github.com/DnCraptor/pico-spec/releases/tag/v.0.3.4
Current master contains version for "green" also: https://github.com/DnCraptor/pico-spec/blob/d5ceecda4def0885b9e3bfaf206c3c362d29c0da/CMakeLists.txt#L39

**Comment by rcmolina** [comment]
@DnCraptor , thanks. It was a picoboot problem, flashed connected from pc and no problem. I'll comment you my tests in a different issue.
