### ISSUE TITLE
Real audio input is not fast enough

### ISSUE THREAD

**Issue by rcmolina** [DnCraptor/pico-spec#3]
@DnCraptor, tested some turbo and otla files but could not get loading errors for them. Max speed I could get is around 3500 bauds. Loading these files from osd is ok.

Find attached here 2 of them for your own testing if you want to:

https://dailyuploads.net/prfn5yvotvqp/Realaudio_tests.rar

Thanks again,

 Rafael

**Comment by DnCraptor** [comment]
Yep, turbo load is not yet fine. Current precision of sampling is about 20ms, and it is 70 CPU tacks (on Z80 3.5MHz), so for cases with records, required more accurate records, it may not work.
Normal tape data is encoded as two 855 T-state pulses for binary zero, and two 1710 T-state pulses for binary one. And plus/minus 70T is quite enough to load such data, but turbo may be much less than 500T for one period, and 70T precision (is more than 10% of error level), that may be not enough.

**Comment by rcmolina** [comment]
Thanks for your work to focus this in.
