### ISSUE TITLE
Keyboard cursors not working for menu Navigation

### ISSUE THREAD

**Issue by rcmolina** [DnCraptor/pico-spec#4]
After pressing F1, you can not go up/down with cursors for selection an option. No problem with Page Up/Down, Enter, etc. Everything working also from emulator with short keys.

Tested with binary 0.3.5 for 2 MB green pico. Tested again with previous binaries (0.3.3 and 0.3.4) and no problem,

**Comment by DnCraptor** [comment]
Pls. try to F1->Reset->Defaults. In case impossible to navigate to, lets remove /spec/storage.nvs on your sd-card

**Comment by rcmolina** [comment]
Joystick also not working, but Reset-Defauls was posible downgrading to 0.3.4. Then it restarted to pico-launcher, and reflashed 0.3.5.

Now cursor keys working again :)

**Comment by DnCraptor** [comment]
![photo_2024-12-05_17-55-36](https://github.com/user-attachments/assets/d6b7a445-0963-4292-82bf-44910ed04972)
FYI: Possible setting, may hang cursor keys, but joystick works for me this time
![photo_2024-12-05_17-57-17](https://github.com/user-attachments/assets/3bd8774b-2618-4858-ac00-f00c2b91df3a)
also, ^ this option may help to W/A this issue.

**Comment by rcmolina** [comment]
Thanks !

**Comment by rcmolina** [comment]
FYI throttling is best translated into spanish as "aceleración".

Thanks for your work.
