### ISSUE TITLE
(new feature) BP for debugger for snap save

### ISSUE THREAD

**Issue by rcmolina** [DnCraptor/pico-spec#5]
@DnCraptor , if not too much work, is it possible to implement a Break Point feature in the debugger so you can get back to main/snapshot menu to save at this point of execution.

Thanks again for considering if possible.

Rafa

**Comment by DnCraptor** [comment]
> @DnCraptor , if not too much work, is it possible to implement a Break Point feature in the debugger so you can get back to main/snapshot menu to save at this point of execution.
> 
> Thanks again for considering if possible.
> 
> Rafa

https://github.com/DnCraptor/pico-spec/releases/tag/v.0.3.6 - lets try it ))

**Comment by rcmolina** [comment]
@DnCraptor 
Oh my god, you are my hero :)
 I'm gonna flash it rigt now and give you feedback.
-
Rafa

**Comment by rcmolina** [comment]
Very happy with this jump forward version. Accidentally hanged when using "-" key many times t ge a very far address, seems a memory exhausted problem. A breakpoint in $FFFF also did not work.
I could put a preakpint at $5B00 and save the custom snapshot, and poke it also. Loaded OK from menu and debugger.
Loaded from external input is not perfect, but happy with it. "ALF machine" expected to load ROM with the menu, but suppose it is included in the firmware (oficial espectrum can load .rom files).

Nice Christmas gift. Feliz Navidad 2024.

**Comment by DnCraptor** [comment]
FYI:
FFFF - means no BP, I will improve it to use some out of uint16_t value for this
"-" - not reproduced yet. May be my build 0.3.7 is already fixed this issue
ALF has other structure of ROMs, than usual speccy, so it is completely separate space of roms.
Hotkeys for reset - F12 in normal mode (in Debug it is used for snapshots)

Nice Christmas

**Comment by rcmolina** [comment]
Just for clarification, when I wrote rom, I referred to cartrdge game, like those16K  prepared to replace  sinclair rom in Paul Farrows page: http://www.fruitcake.plus.com/Sinclair/Interface2/Cartridges/Interface2_RC_New_3rdParty_GameConversions.htm

**Comment by rcmolina** [comment]
@DnCraptor, understood. BTW, is it possible to endend in debugger + and - memory functions toba full page with Av Pg and Re Pg ??

**Comment by DnCraptor** [comment]
[VGA-0.3.7-5.zip](https://github.com/user-attachments/files/18157651/VGA-0.3.7-5.zip)
lets try it

**Comment by rcmolina** [comment]
@DnCraptor, :) just flashed. Tested Pg Up/Down. I think - and + functions should be swapped.
More intuititive with key positions (for me Page Up and Down are fine:
"-"  climb up (to zero) and Page Up
"+" (to FFFF) and Page Down

Now BP at $FFFF works fine. I'll do more tests in a minute

**Comment by DnCraptor** [comment]
FYI: cursor UP/DOWN arrays also works, so you may not use +/- ))

**Comment by rcmolina** [comment]
Tested UP/DOWN, great, more intuitive.

**Comment by DnCraptor** [comment]
FYI: pico-launcher is slightly outdated software, let try murmulator-os instead: https://github.com/DnCraptor/murmulator-os/releases/tag/v.0.3.3
In default configuration you will return to mc, and on F10 from mc, you will return back to pico-spec

**Comment by rcmolina** [comment]
@DnCraptor , thanks promise to ckeck it after Christmas. Something more to check now when testing TURBO feature: 
-Reset spectrum, now in Rom basic mode
-Activate stas with F8
- Activate turbo Alt-F2 several times until max speed (green). Keyboard is not responsive at max speed, in other speed keyboard input is working.

+Testing Pause key. Fn keys not working in Pause mode. You can only leave pause mode with Space or Enter, not with Pause, This can lead us to potential hanging in Turbo max speed (keyboard input is not working), and need shutting down.

**Comment by DnCraptor** [comment]
FYI: For high speed turbo, it is better to use pico2 board. pico is not in time to process all req. for a frame, and FSP fast degradating, CPU IDL tacts number are turned to negative value. May be, it is good idea to limit turbo by only one stage (7MHz - red on F8)
Ok. Pause, really may be improved, you are right.

**Comment by rcmolina** [comment]
Thanks, yes it sounds really good if we could make an snapshot, or a screen dump also in Pause mode

**Comment by DnCraptor** [comment]
> Testing Pause key. Fn keys not working in Pause mode. You can only leave pause mode with Space or Enter, not with Pause, This can lead us to potential hanging in Turbo max speed (keyboard input is not working), and need shutting down.

[pico-spec-2048-378-VGA-1.2.4-10.uf2.zip](https://github.com/user-attachments/files/18239700/pico-spec-2048-378-VGA-1.2.4-10.uf2.zip)
Lets try this build. It is attemp to improve pause-logic.

**Comment by rcmolina** [comment]
@DnCraptor , thanks for your great work. Gonna test in a minute :)

**Comment by rcmolina** [comment]
@DnCraptor , Meery Christmas.
Someting strange when pressing again pause key to get back to live state... Key buffer seem not cleaned.
1)Load alien8.tap
2)start the game with keyboard, afer moving the robot press Pause Key.
3) Press pause key again to get back to Live mode.
4) Robot is rolling all the time, but moving keys also working working.
5)Reset F11 does not seem to sove the issue until power off
6) If using kempston joystick, the issue does not arise, with F11 + keyboard still there,,,,

**Comment by rcmolina** [comment]
Hanging at max speed with pause is solved :)

**Comment by rcmolina** [comment]
@DnCraptor , should be possible a new confuration option for tap loading, that instead of automatic execution at file end, do a jump to debugger or to pause mode? this will be helpful to get a perfect snapshot.

**Comment by rcmolina** [comment]
Strange behaviout with BreakPoints. Tested with Alien8.tap: Starting point at $6300
Setting some BreakPoint Addresses do not work. Procedure:
Reset with F11
Set Break Point
Load Alien8.tap
Expected behaviour is to stop at the address BreakPoint.

$6300  not working
$A631  not working
$A63A not working
$A63B  not working
$CE56 not working
$CE58 WORKING until $CE5F not working again

**Comment by DnCraptor** [comment]
Not reproduced, because I have no exact file you mentioned. But slightly improved breakpoints logis:
[pico-spec-4096-408-VGA-1.2.4-16.uf2.zip](https://github.com/user-attachments/files/18247503/pico-spec-4096-408-VGA-1.2.4-16.uf2.zip)

**Comment by rcmolina** [comment]
@DnCraptor , attached alien8.zip with files to debug BreakPoints:
[Alien8.zip](https://github.com/user-attachments/files/18249749/Alien8.zip)
Bad news, issues still there:
1)Pause+Unpause after reset in Basic. (SS continuous activated i.e. shifted). If you press A you get STOP instead of NEW. Work around press cntrl-A to make an STOP to restore SymbolShift State to none.
Also inside alien8 game, pause and unpause, you get a mad rolling robot :)
2)BreakPoints not performed with z80 or tap, and some proposed improvements. 
2.1) Minor aestetic in debug window, register IX shows as iX
2.2) Not shown interrupts enabled or disabled flag IM (EI/DI) in debug window. When stepping CPU, you loose control if EI enabled (jumps to 0038h for instance).  ¿only step-into implemented? ¿any chance to implement step-over to jump to next instruction? I know step over not needed if you put a BP to next instruction, but not working well now,
2.3) Swap from instruction view to memory dump view to check easily strings, etc ¿any chance?
2.4) One more test: 
2.4.1) Reset and set BP to $5B00
2.4.2) Load **alien83.z80**
2.4.3) Breakpoint works and state is interrupt enabled (EI)
2.4.4) If you step into, you loose control and jumps to $0038 , so as work around with interrupts enabled, we are going to set BP at $5B03 with Alt-F7
2.4.5) Leave with Esc the debug window, expecting to stop at $5B03 but the spaceship is without control, never returned :)

**Comment by DnCraptor** [comment]
[pico-spec-2048-378-PWM-VGA-1.2.5-5.uf2.zip](https://github.com/user-attachments/files/18262249/pico-spec-2048-378-PWM-VGA-1.2.5-5.uf2.zip)
FYI: for SS on unpause looks solved ^
for others - not yet processed.

**Comment by DnCraptor** [comment]
FYI: it is better to review latest builds from our Telegram chat: https://t.me/ZX_MURMULATOR/59454/184965

**Comment by rcmolina** [comment]
@DnCraptor , thanks :) I can find the files in telegram, but I can not read russian yet ja,ja

**Comment by DnCraptor** [comment]
FYI: google chome provides tranclate on page basis. Or on selected words bases.

**Comment by DnCraptor** [comment]
@rcmolina , https://t.me/ZX_MURMULATOR/59454/184972 - step-over in case ALT+Space pressed, (complicated impl.)
It waits PC+3, but only 64k command executions (it may be endless), after this it returts from Debug mode, but set a BP to desired address.

**Comment by rcmolina** [comment]
@DnCraptor , thanks. Happy :)
