### ISSUE TITLE
rp2040-pizero

### ISSUE THREAD

**Issue by 8tpercent** [DnCraptor/pico-spec#6]
Hi,

Jut tried a few of the released but just get a black screen:

https://www.waveshare.com/rp2040-pizero.htm

Will there be support for the above board?

Thanks

**Comment by DnCraptor** [comment]
This board is unsupported now. Murmulator board only (see https://github.com/AlexEkb4ever).

**Comment by DnCraptor** [comment]
@8tpercent lets try this:
[z0p1-spec-2048-PWM-HDMI-1.2.A.zip](https://github.com/user-attachments/files/19820617/z0p1-spec-2048-PWM-HDMI-1.2.A.zip)
2 versions, with different CPU freq. On my PiZero 252 works, but 378 is not.
For other devices:
PS/2 keyboard - GP 0/1
NES_GP_CLK=7
NES_GP_LAT=8
NES_GP_DATA=9
NES_GP_DATA2=10 (second joyst)
BEEPER_GR=11
PWM_GP_R=12
PWM_GP_R=13
LOAD_WAV_PIO=17

**Comment by DnCraptor** [comment]
Note bene: this firmware supports USB OTG hub, so you may use USB HID keyboard/joystick (not dualshock)
